### ISSUE TITLE
New arduino Nano boards have new bootloader

### ISSUE THREAD

**Issue by ivankravets** [platformio/platform-atmelavr#103]
PIO Home feedback:

> New arduino Nano boards have new bootloader. Uploading code fails if  software tries to compile for old ATMEGA328P. Same problem if using  Arduino IDE without up to date "Arduino AVR boards"

**Comment by rcjcooke** [comment]
Couldn't find an "upvote" mechanism on here so posting instead. Can't seem to upload to a new Nano through PlatformIO on VSCode. Uploading works fine on Arduino IDE. My guess is that it's the new bootloader on the Nano that's the problem. I get the same problems as mentioned here: https://community.platformio.org/t/nano-328p-boot-loader/3997

**Comment by ivankravets** [comment]
Please use new board manifest by id `nanoatmega328new` and name `Arduino Nano ATmega328 (New Bootloader)`
