### ISSUE TITLE
Boards.h file doesn't have ATMega1284P or ATMega1284 defined for Sanguino

### ISSUE THREAD

**Issue by Maddog2050** [platformio/platform-atmelavr#109]
Hi,

I have found that the Boards.h file doesn't have a definition for the ATMega1284P or ATMega1284 for the Sanguino boards as I got the error below:

In file included from C:\Users\auser\.platformio\packages\framework-arduinoavr\libraries\Firmata\Firmata.h:17:0,
from C:\Users\auser\.platformio\packages\framework-arduinoavr\libraries\Firmata\Firmata.cpp:18:
C:\Users\Auser\.platformio\packages\framework-arduinoavr\libraries\Firmata\Boards.h:770:2: error: #error "Please edit Boards.h with a hardware abstraction for this board"
#error "Please edit Boards.h with a hardware abstraction for this board"

Please could you update the Boards.h file so that the Sanguino definition also includes the ATMega1284P or ATMega1284 as per the below.

```
// Sanguino
#elif defined(__AVR_ATmega644P__) || defined(__AVR_ATmega644__) || defined(__AVR_ATmega1284P__) || defined(__AVR_ATmega1284__)
```

Thanks

Adam

**Comment by ivankravets** [comment]
Please move issue to https://github.com/firmata/arduino
