### ISSUE TITLE
Invalid Board JSON for Sparkfun Pro Micro 5V

### ISSUE THREAD

**Issue by R0ll1ngSt0ne** [platformio/platform-atmelavr#132]
Sparkfun Pro Micro 5V board claims PIDs 0x9205 and 0x9206.

The board JSON included with platformio (sparkfun_promicro16.json) lists incorrect PIDs:

    "hwids": [
      [
        "0x1B4F",
        "**0x9203**"
      ],
      [
        "0x1B4F",
        "**0x9204**"
      ],

The above PIDs are for 3.3V version of the board, not 5V.

**Comment by ivankravets** [comment]
Thanks!

**Comment by R0ll1ngSt0ne** [comment]
You are welcome!

**Comment by R0ll1ngSt0ne** [comment]
I think there is still a problem with the JSON:

The PIDs claimed by Pro Micro 5V are PID: 0x9205 (**bootloader**); 0x9206 (**sketch**)

However, JSON now lists the PIDs in this order:

>     "hwids": [
>       [
>         "0x1B4F",
>         "0x9205"
>       ],
>       [
>         "0x1B4F",
>         "0x9206"
>       ],

It seems that when writing a sketch to the board, platformio writes the _first PID_ to to the board - causing the board to use  bootloader PID for sketch. I think the order of pids in the JSON should be reversed.

Thanks,

Michael

**Comment by R0ll1ngSt0ne** [comment]
Is there a way to specify in the JSON which if HWIDs are for bootloader and which are for a sketch?

**Comment by ivankravets** [comment]
Hm... But we don't support flashing of bootloader. So, we can use HWID/PID for sketch?

**Comment by ivankravets** [comment]
Please re-test with the upstream version  http://docs.platformio.org/en/latest/platforms/atmelavr.html#upstream
