### ISSUE TITLE
RobotDyn UNO R3 SMD ATmega328 - problem with auto detection

### ISSUE THREAD

**Issue by mgawron86** [platformio/platform-atmelavr#133]
Hi. I ordered new Arduino UNO board(https://robotdyn.com/uno-r3-smt-atmega328-usb-serial-ch340g-micro-usb.html) and it seems that auto detection does not work for my board version.

Terminal output:
```
/dev/ttyUSB1
------------
Hardware ID: USB VID:PID=1A86:7523 LOCATION=1-1.2
Description: USB2.0-Serial
```
Thank you in advance !

**Comment by ivankravets** [comment]
> Most of the Chinese clones use the CH340 now so they are VID:1A86, PID:7523.

This is generic `CH340` TTL which can be used in any board, not only Uno. You can specify custom upload port with http://docs.platformio.org/en/latest/projectconf/section_env_upload.html#upload-port
