### ISSUE TITLE
Update MightyCore

### ISSUE THREAD

**Issue by MCUdude** [platformio/platform-atmelavr#148]
I've just released a [new version of MightyCore](https://github.com/MCUdude/MightyCore/releases/tag/v2.0.2) which fixes some PlatformIO related issues. @ivankravets maybe we should rename the JSON files just like we did with MiniCore? I can submit a PR for this if you want.

**Comment by ivankravets** [comment]
Resolved with https://github.com/platformio/platform-atmelavr/commit/79e5ef5aa05f68f3fe3a2599251f8d5e31084c99


> maybe we should rename the JSON files just like we did with MiniCore

Yes, please provide PR and I'll make a new release. Thanks!
