### ISSUE TITLE
Add support for ATMEGA640

### ISSUE THREAD

**Issue by dmsherazi** [platformio/platform-atmelavr#149]
Add support for megacore an Arduino core for ATmega64, ATmega128, ATmega640, ATmega1280, ATmega1281, ATmega2560, ATmega2561, AT90CAN32, AT90CAN64 and AT90CAN128, all running Optiboot flash.

**Comment by MCUdude** [comment]
@ivankravets is this as simple as adding the correct board JSON files? I can submit a PR for this if you like.

**Comment by ivankravets** [comment]
Maybe, rename existing manifests?

**Comment by MCUdude** [comment]
But how about the users who use PlatformIO with Arduino Mega? wouldn't this cause issues if we suddenly rename and restructure the existing board manifests? Isn't it better if I just submit a PR for the new ones, and you can "clean up" the list afterward? Of course, megacore128.json will be renamed by me.

**Comment by ivankravets** [comment]
You are right, let have new manifests.

**Comment by MCUdude** [comment]
@ivankravets this issue can be closed now 👍

**Comment by ivankravets** [comment]
Thanks!
