### ISSUE TITLE
Contributing a board with custom pins_arduino.h for Arduino Framework

### ISSUE THREAD

**Issue by Rodmg** [platformio/platform-atmelavr#15]
Hello, I would like to contribute the support for a board called [Altair](http://www.aquila.io/en), I successfully got it working by making a custom board json file and putting it in ~/.platformio/boards and manually copying the custom pins_arduino.h to ~/.platformio/packages/framework-arduinoavr/variants/altair/.

Here are the files and instructions to manually install it: https://github.com/Rodmg/altair-platformio

However this is not convenient as I have to copy the pins_arduino.h file again every time the framework is updated.

I've been looking at the platform-atmelavr (this) github repository and I know that I could make a pull request for adding the board json definition, however I cannot find where to put the pins_arduino.h file.

Where are the board variant files located?

Thank you.

**Comment by ivankravets** [comment]
The repo is created. Please make PR to it.

https://github.com/platformio/platformio-pkg-framework-arduinoavr
