### ISSUE TITLE
This line breaks uploads using usbasp.

### ISSUE THREAD

**Issue by rkit1** [platformio/platform-atmelavr#155]
I kept getting this error while trying to upload using usbasp.
> avrdude: verification error, first mismatch at byte 0x002e
          0x38 != 0x3c

After removing this line locally the problem was fixed.
https://github.com/platformio/platform-atmelavr/blob/acca29b9b3864a869d8bfc7456915d2e4c421e8f/builder/main.py#L42

>  -D                         Disable auto erase for flash memory

**Comment by ivankravets** [comment]
Please use `pio run -t program` instead of `upload`.
