### ISSUE TITLE
Board Support request: Prusa3d printers

### ISSUE THREAD

**Issue by xoxota99** [platformio/platform-atmelavr#166]
Requesting board support for prusa 3D printers (EINSY , RAMBO). See https://raw.githubusercontent.com/prusa3d/Arduino_Boards/master/IDE_Board_Manager/package_prusa3d_index.json

**Comment by Deneteus** [comment]
@ivankravets Do we know this request is at the moment? I want to be able to use Platformio for building Prusa Mk3 firmware.

**Comment by bgiot** [comment]
This support has been added for a while... this issue can be closed.
