### ISSUE TITLE
Update Sanguino variants/pins_arduino.h

### ISSUE THREAD

**Issue by pfeerick** [platformio/platform-atmelavr#182]
The `pins_arduino.h` included in the `framework-arduinoavr` package for the sanguino variant is a wee bit outdated - and doesn't include changes from Dec 2016!

https://github.com/Lauszus/Sanguino/blob/master/variants/sanguino/pins_arduino.h

**Comment by valeros** [comment]
Resolved in the latest `framework-arduino-avr` package
