### ISSUE TITLE
MCUdude MicroCore for better ATtiny13 support

### ISSUE THREAD

**Issue by MCUdude** [platformio/platform-atmelavr#193]
One thing that has been requested over at the [MicroCore repo](https://github.com/MCUdude/MicroCore/) is PlatformIO. If you don't know MicroCore, it's a very good ATtiny13 core package for Arduino IDE. **FAR** superior to core13, which the current PlatformIO implementation uses. I've also made sure that the fuses.py scripts supports the ATtiny13, so it shouldn't be too much work for you to implement this. I will also create detailed PlatformIO documentation for MicroCore so users easily take advantage of its features.

However, I have some work to do. I want the core to be as flexible as possible and make good use of PlatformIO's flexibility. I will have to do a lot of testing, and preferably a new MicroCore release to prepare for PlatformIO support.

The question is: Can I create my own private MicroCore implementation so I can test and fine-tune various new features? When this is implemented I'll recommend you to replace the existing implementation with the new one. There's literally no reason to keep the old one. It's old, outdated, and not very well written IMO.

What do you think? 🙂

**Comment by valeros** [comment]
Sounds great! If you want to test it locally, just create a new package `framework-arduino-avr-microcore` by analogy with your previous cores (make sure package.json is modified accordingly). Then you will need to specify this new package and its version  in `platform.json` file. It should be located somewhere here `~/.platformio/platforms/atmelavr/platform.json`.  After that you can choose your core via:
```
board_build.core = MicroCore
board_build.variant = attiny13
```
Hope it helps!
