### ISSUE TITLE
Could not find the package with tool-avrdude for linux_armv7l

### ISSUE THREAD

**Issue by mdevaev** [platformio/platform-atmelavr#211]
On Raspberry Pi 4 (armv7l) I can't upload AVR firmware:
```
Tool Manager: Installing tool-avrdude @ ~1.60300.0
Error: Could not find the package with 'tool-avrdude @ ~1.60300.0' requirements for your system 'linux_armv7l'
```
The error appeared in platformio 5.0.0. 4.3.1 works fine. It's possible that the problems are also showing up for another architecture (armv6h), but I haven't had a chance to check.

UPD: Didn't use any magic, just common project config:
```
...
platform = atmelavr
board = micro
framework = arduino
...
```

**Comment by aberix** [comment]
I experienced the same issue, when I tried to upload to an target using a raspberry pi 3 as host.

Would it be a solution to downgrade platformio to 4.x?

**Comment by mdevaev** [comment]
> Would it be a solution to downgrade platformio to 4.x?

Yes, 4.x is working.

**Comment by aberix** [comment]
Thanks, that helped for the moment. I am waiting for a fix and will be ready to support testing the fix.

**Comment by valeros** [comment]
Hi guys! Sorry for the issue, the package for `linux_armv7l` has been restored, should work now.

**Comment by gwendolynbrook** [comment]
I'm seeing the same issue today for armv7 

`toolchain-atmelavr @ 1.40902.0 has been successfully installed!
 PackageManager: Installing tool-avrdude @ ~1.60300.0
 Warning! Package Mirror: The 'sha1' sum '64f2bb7dc9a6c27747095694f2f3f270a9f34a50' of downloaded file 'tool-avrdude-linux_armv6l-1.60300.200527.tar.gz' is not equal to remote '75a72f9c9a17d6a96dabcd15f64e12e45c489b4f'
 Looking for another mirror...
 Error: Could not install 'tool-avrdude' with version requirements '~1.60300.0' for your system 'linux_armv7l'. `
