### ISSUE TITLE
*** [upload] Error 309 at digispark attiny85

### ISSUE THREAD

**Issue by Kamilake** [platformio/platform-atmelavr#250]
![image](https://user-images.githubusercontent.com/15166740/112832028-b557eb00-90cf-11eb-9d57-c87a5c20ded5.png)
RAM:   [          ]   1.8% (used 9 bytes from 512 bytes)
Flash: [=         ]   5.9% (used 352 bytes from 6012 bytes)
Configuring upload protocol...
AVAILABLE: micronucleus
CURRENT: upload_protocol = micronucleus
Uploading .pio\build\digispark-tiny\firmware.hex
*** [upload] Error 309

Whenever I hit the upload button to upload code, I get the following message: This is not a driver issue, the same project is uploaded normally in different environments.
Two different environments have the same version of Windows and the same version of pio,code.
What makes this difference? I couldn't upload the code in any way.
![image](https://user-images.githubusercontent.com/15166740/112832358-2a2b2500-90d0-11eb-8ed2-264d9db461f4.png)

The code I'm trying to upload is blink.

**Comment by valeros** [comment]
https://community.platformio.org/t/how-to-program-attiny-85-with-platformio-vscode/18957/8 might contain possible solutions.

**Comment by Kamilake** [comment]
> https://community.platformio.org/t/how-to-program-attiny-85-with-platformio-vscode/18957/8 might contain possible solutions.
Thanks for the quick advice. I will be testing Verbose mode soon. And I will give you the results.
![image](https://user-images.githubusercontent.com/15166740/112946192-3070de00-9170-11eb-9298-45bb0348ed8a.png)

**Comment by Kamilake** [comment]
![image](https://user-images.githubusercontent.com/15166740/112981502-409bb400-9196-11eb-8e1a-b6b255194e5c.png)


> https://community.platformio.org/t/how-to-program-attiny-85-with-platformio-vscode/18957/8 might contain possible solutions.
I still haven't got any information to fix the problem even in Verbose mode.. and Reinstalling the PIO didn't work for me.

`*** [upload] Error 309`

This is a problem before the USB driver.
There seems to be a problem with the micronucleus itself.
Please ask me for any additional information you need. I will answer immediately.
Thanks in advance.

**Comment by Kamilake** [comment]
![image](https://user-images.githubusercontent.com/15166740/113289075-afaa1180-932a-11eb-8cfe-a09989235457.png)

Just before, I saw a message on my console that seems to be downloading a library of something.
It soon disappeared and I couldn't find it on all tabs.(I saw links like adafruit etc.)
When I hit the upload button again everything worked fine.
My logs appear to have been deleted automatically, so I can't tell you how to fix it.
I will soon leave the unstable platform and return to the legacy Arduino IDE. (I've already found more than 10 bugs, and I have to be uncomfortable because I don't have the ability to fix them.)
Finally, please feel free to tell me if you need anything.
