### ISSUE TITLE
avr-gdb depends on libncurses.so.5 and libtinfo.so.5

### ISSUE THREAD

**Issue by neildarlow** [platformio/platform-atmelavr#256]
Hi,

I am running PlatformIO from VSCodium in flatpak format. There is an issue with avr-gdb requiring libncurses and libtinfo with major version number of 5 as follows:

neil@satellite:~$ ldd .platformio/packages/toolchain-atmelavr/bin/avr-gdb
linux-vdso.so.1 (0x00007ffd5605a000)
libncurses.so.5 => not found
libtinfo.so.5 => not found
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8f18297000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8f180a5000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8f1809f000)
/lib64/ld-linux-x86-64.so.2 (0x00007f8f183ff000)

Could avr-gdb be updated to link against libncurses.so.6 and libtinfo.so.6 please?

I am making this request because the runtime used by the flatpak (org.freedesktop.Sdk/Platform version 20.08) includes these libraries at major version 6. I can install the version 5 libraries on the host but they are not accessible within the flatpak.

Regards,
Neil Darlow

**Comment by valeros** [comment]
Hi @neildarlow ! The GDB binary is part of the toolchain, so it's not possible to update it at the moment. I'm not sure whether it will help, but you can try this package:
```
platform_packages =
   toolchain-atmelavr @ ~2.70300.0
```

**Comment by neildarlow** [comment]
Hi @valeros,

Thank you but that caused more issues. For now I've switched from VSCodium in flatpak to AppImage and installed those legacy libraries.

Not an ideal solution but it works.

ATB,
Neil Darlow

**Comment by Saganesque** [comment]
I am running into the same issue using PlatformIO on VSCode
