### ISSUE TITLE
Usbasp upload parameters may be wrong

### ISSUE THREAD

**Issue by maxpowel** [platformio/platform-atmelavr#26]
Hello! I cant upload an sketch using this configuration:

```
[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
upload_protocol = usbasp
```
I got the message "0x04 != 0x0c" when it verifies the flash.

If I upload the firmware manually with this command everything is fine:
```
avrdude -p m2560 -c usbasp -F -U flash:w:/home/alvaro/atom/megaasp/.pioenvs/megaatmega2560/firmware.hex
```
I dont really know how platformio manages the uploads, I just detected this and notify you. I can only provide the command above that works fine.
My platformio installation just updated yesterday and before that the skteches were uploading fine.

Thank you

**Comment by ivankravets** [comment]
1. Use `pio run -t program`
2. Add to your config `upload_flags = -F`
