### ISSUE TITLE
ATtiny85 runs at half speed due to bad clock source setting

### ISSUE THREAD

**Issue by Granjow** [platformio/platform-atmelavr#264]
Commit 012de336af56472e65e2db2e6c2d95d9a137803d, which was released with version 3.4.0, breaks ATtiny support when using frequencies other than 16 MHz. When setting `board_build.f_cpu = 8000000L`, the code is still compiled for 16 MHz due to the clock source and therefore the code only runs half as fast.

I don't know where the correct place to fix #255 is, but the attiny85.json definitely isn't because it is not even possible to override the clock source setting with `board_build.clocksource = 0`. A local workaround would probably be to set `board_build.clocksource = 6` e.g. for the ATtiny85 in the `platformio.ini`.

**Comment by rholder** [comment]
@Granjow Thanks for the detailed description here as it helped me get a project build fixed much faster than I expected. I've opened up a PR with your suggested change.

**Comment by ikatkov** [comment]
**For people who came here from a websearch**
if your attyiny85 runs at half speed through Platformio and works fine through Arduino IDE

- either switch to the dev version of the platform-atmelavr
- or edit your local file in $HOME/.platformio/platforms/atmelavr/boards/attiny85.json and remove "-DNEOPIXELPORT=PORTB -DCLOCK_SOURCE=6"

**Comment by ur99999999** [comment]
> 
temporary fix: add next line to platformio.ini [env:...]
`build_flags = -DCLOCK_SOURCE=0`
