### ISSUE TITLE
Ou installer le dossier firmework arduinoavr/ Where to install firmwork folder arduinoavr

### ISSUE THREAD

**Issue by OmSenn** [platformio/platform-atmelavr#290]
bonjour 

Pouvez-vous me dire ou installer le dossier firmework arduinoavr pour vscode 
je suis sur windows et un peu perdu
merci 

-----

hello

Can you tell me where to install firmwork folder arduinoavr for vscode
I'm on windows and a little lost
thank you

**Comment by valeros** [comment]
Hi @OmSenn , the package is located here `c:\Users\YOUR_USER\.platformio\packages\framework-arduino-avr`

**Comment by OmSenn** [comment]
Thank you very much, I tried but I always have an error that I do not understand, to compile the marlin of the ender 3 pro in V1.1.6.2

when i do a - pio pkg update:
Resolving FYSETC_F6_14 dependencies...
Error: Unknown board ID 'fysetc_f6_14'
PS C:\Marlin\Marlin-bugfix-2.0.xXX> 


and a compilation in marlin from vscode

PS C:\Marlin\Marlin-bugfix-2.0.xXX> platformio run -e melzi_optimized
Warning! Ignore unknown configuration option `monitor_flags` in section [env]
Warning! `src_filter` configuration option in section [env:DUE] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:DUE_USB] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:DUE_debug] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:SAMD51_grandcentral_m4] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:STM32F4] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:STM32F7] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:malyan_M300] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:esp32] is deprecated and will be removed in the next release! Please 
use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:teensy31] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:teensy35] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_build_flags` configuration option in section [env:linux_native] is deprecated and will be removed in the next release! Please use `build_src_flags` instead
Warning! `src_filter` configuration option in section [env:linux_native] is deprecated and will be removed in the next release! 
Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:include_tree] is deprecated and will be removed in the next release! 
Please use `build_src_filter` instead
Processing melzi_optimized (platform: atmelavr; board: sanguino_atmega1284p; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
In file included from c:\marlin\marlin-bugfix-2.0.xxx\marlin\src\hal\avr\hal.h:21:0,
                 from c:\marlin\marlin-bugfix-2.0.xxx\marlin\src\hal\hal.h:26,
                 from c:\marlin\marlin-bugfix-2.0.xxx\marlin\src\inc\marlinconfig.h:30,
                 from buildroot/share/PlatformIO/scripts/common-dependencies.h:29:
c:\marlin\marlin-bugfix-2.0.xxx\marlin\src\hal\shared\marduino.h:36:10: fatal error: Arduino.h: No such file or directory

*****************************************************************
* Looking for Arduino.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Arduino.h"
* Web  > https://registry.platformio.org/search?q=header:Arduino.h
*
*****************************************************************

 #include <Arduino.h>  // NOTE: If included earlier then this line is a NOOP
          ^~~~~~~~~~~
compilation terminated.
CalledProcessError: Command '"C:\Users\Caritas\.platformio\packages\toolchain-atmelavr\bin\avr-g++.exe" -D__MARLIN_FIRMWARE__ -D__MARLIN_DEPS__ -w -dM -E -x c++ buildroot/share/PlatformIO/scripts/common-dependencies.h' returned non-zero exit status 1.:    
  File "C:\Users\Caritas\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 186:
    env.SConscript(item, exports="env")
  File "C:\Users\Caritas\.platformio\packages\tool-scons\scons-local-4.4.0\SCons\Script\SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\Users\Caritas\.platformio\packages\tool-scons\scons-local-4.4.0\SCons\Script\SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "C:\Marlin\Marlin-bugfix-2.0.xXX\buildroot\share\PlatformIO\scripts\common-dependencies.py", line 247:
    apply_features_config()
  File "C:\Marlin\Marlin-bugfix-2.0.xXX\buildroot\share\PlatformIO\scripts\common-dependencies.py", line 133:
    if not env.MarlinFeatureIsEnabled(feature):
  File "C:\Users\Caritas\.platformio\packages\tool-scons\scons-local-4.4.0\SCons\Util.py", line 737:
    return self.method(*nargs, **kwargs)
  File "C:\Marlin\Marlin-bugfix-2.0.xXX\buildroot\share\PlatformIO\scripts\common-dependencies.py", line 216:
    load_marlin_features()
  File "C:\Marlin\Marlin-bugfix-2.0.xXX\buildroot\share\PlatformIO\scripts\common-dependencies.py", line 204:
    define_list = run_preprocessor(env)
  File "C:\Marlin\Marlin-bugfix-2.0.xXX\buildroot\share\PlatformIO\scripts\preprocessor.py", line 43:
    define_list = subprocess.check_output(cmd, shell=True).splitlines()
  File "C:\Users\Caritas\.platformio\python3\lib\subprocess.py", line 424:
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Caritas\.platformio\python3\lib\subprocess.py", line 528:
    raise CalledProcessError(retcode, process.args,
================================================== [FAILED] Took 3.52 seconds ==================================================
Environment      Status    Duration
---------------  --------  ------------
melzi_optimized  FAILED    00:00:03.516
============================================ 1 failed, 0 succeeded in 00:00:03.516 ============================================
