### ISSUE TITLE
Flash is not erased when uploading hexfile

### ISSUE THREAD

**Issue by artur-scholz** [platformio/platform-atmelavr#3]
Using the Platformio IDE integrated in Atom, when performing "Upload" the command line output shows that the "-D" flags is used with the avrdude tool. 

This disables auto erase for flash. However, it is essential that the flash is erased before uploading new code into it. I am using a bare Atmega48 (no Arduino). I did not find a way to remove this flag anywhere in the platformio config files..

**Comment by ivankravets** [comment]
Use `program` instead `upload`. See http://docs.platformio.org/en/latest/platforms/atmelavr.html#upload-using-programmer

`program` is bare target and you can customize it manually using `upload_flags`.

**Comment by artur-scholz** [comment]
Great! Is it possible to have this integrated in the left toolbar? Otherwise I need to select "PlatformIO: Upload using programmer" either via left bottom option or via F7.

**Comment by ivankravets** [comment]
Em.... Very interesting question 👍 There are a lot of solutions to do it 😄 

How about to create [extra_script](http://docs.platformio.org/en/latest/projectconf.html#extra-script) and override with custom upload command?

See my example here https://github.com/platformio/platformio/issues/247#issuecomment-118169728

**Comment by artur-scholz** [comment]
Thanks for the fast reply. Honestly I want to avoid tinkering with scripts. So I will use the available option then.

**Comment by ivankravets** [comment]
Another option is to use [targets](http://docs.platformio.org/en/latest/projectconf.html#targets). In this case, "Build" button will have "program" behaviour.

For example,
```ini
[env:my]
targets = program
```
