### ISSUE TITLE
Update MCUdude cores (yet again, sorry)

### ISSUE THREAD

**Issue by MCUdude** [platformio/platform-atmelavr#302]
@valeros right after you added the latest version of all my AVR Arduino cores to PlatformIO, I discovered a bug that had to be dealt with. I've also pulled in some corefiles-related changes from the official Arduino AVR core, so the cores should be even more reliable.

Sorry for the fuzz, but this will be the last release before I start the migration from Optiboot to [Urboot](https://github.com/stefanrueger/urboot), which is a much better, faster, and sleeker bootloader for AVRs.

|                      | Previous version | New version |
|-------------|-----------------|--------------|
| MightyCore | 2.2.0                    | 2.2.1               |
| MegaCore   | 2.2.1                     | 2.2.2              |
| MiniCore      | 2.2.0                    | 2.2.1              |
| MajorCore   | 2.2.0                     | 2.2.1             |

**Comment by valeros** [comment]
Thanks, updated!
