### ISSUE TITLE
PlatformIO passes the wrong -mmcu flag for the assembler (ATmega328PB)

### ISSUE THREAD

**Issue by PeterMaes** [platformio/platform-atmelavr#317]
It seems PlatformIO can't compile assembler files for ATmega328PB

https://community.platformio.org/t/avr-assembler-code-for-atmega328pb

**Comment by PeterMaes** [comment]
I am using .s , but I have also tried .asm as extension

**Comment by valeros** [comment]
Try `.S` in the upper case.

**Comment by PeterMaes** [comment]
OK, that seems to be the sollution to have a succesfull compilation of the assembler code.
Maybe something to improve or a better way in error description would help.

Issue resolved ! Thx for the support !
