### ISSUE TITLE
Is there a possibility to detemine the selected board in sources

### ISSUE THREAD

**Issue by willie68** [platformio/platform-atmelavr#331]
if hav written a small program, which works on the digispark/digistump , the small attiny85 board.  Because of some problems with the nucleonus bootloader, i had to use a different pin mapping for my application. 
But i have the option to use another board, which uses another pin mapping. 
Is there a possibility to do something like `#ifdef __digispark-tiny__` in my sources (an eqivalent to `#ifdef __AVR_ATtiny85__` ) to address this change in pin mapping?
I search a long time, but i didn't find any solution.

**Comment by valeros** [comment]
Hi @willie68, you can use `ARDUINO_AVR_DIGISPARK` macro to distinguish the `digispark-tiny` board from other targets (note that `digispark-pro` also uses the same macro).

**Comment by willie68** [comment]
Thank you.
