### ISSUE TITLE
Modifying gcc-flags.json

### ISSUE THREAD

**Issue by matthewcarroll** [platformio/platform-atmelavr#38]
Modifying gcc-flags.json seems to have no effect on the build. Changing any setting in gcc-flags.json is unreflected in the verbose build output of a project (e.g. changing `gccDefaultCppFlags`). How can gcc-flags.json be enabled?

**Comment by ivankravets** [comment]
http://docs.platformio.org/en/latest/projectconf.html#build-flags

**Comment by matthewcarroll** [comment]
Yes, I saw that. I thought that gcc-flags.json was editable given the instructions to edit gcc-flags.json for linting:
http://docs.platformio.org/en/latest/ide/atom.html?highlight=gcc-flags#smart-code-linter
http://docs.platformio.org/en/latest/ide/atom.html?highlight=gcc-flags#force-arduino-file-as-c

**Comment by matthewcarroll** [comment]
Thanks. Yes, I saw that. I thought that gcc-flags.json was supposed to be editable given the instructions to edit it for linting:
http://docs.platformio.org/en/latest/ide/atom.html?highlight=gcc-flags#force-arduino-file-as-c
http://docs.platformio.org/en/latest/ide/atom.html?highlight=gcc-flags#smart-code-linter

**Comment by ivankravets** [comment]
Thanks, I've just updated a docs:

* https://github.com/platformio/platformio-core/commit/ba750f0eee749863f827728c3725b8d5a14b0f63
