### ISSUE TITLE
add support for all 100 pins on ATmega 2650

### ISSUE THREAD

**Issue by gratefulfrog** [platformio/platform-atmelavr#50]
The Arduino implementation only provides access to some of the pins. These are currently available on platformIO as well.

However, I need to be able to address all 100 pins, as provided by the [MegaCore](https://github.com/MCUdude/MegaCore/tree/avr-100-pin) package.

I would be great if this could be integrated into PlatformIO.

Thanks,
Bob

**Comment by valeros** [comment]
Looks like support for this targets was released in https://github.com/platformio/platform-atmelavr/releases/tag/v1.15.0
