### ISSUE TITLE
Blink-example with ATTiny85

### ISSUE THREAD

**Issue by kkrischker** [platformio/platform-atmelavr#57]
I tried the blink example with an ATTiny85 (Board: Generic ATTiny85), but the blink interval is 8 times slower than expected. I read out the fuses because I thought the clock is only 1 MHz instead of 8 MHz as described in the documentation. But the values of the read out fuses are ok: low=0x62, high=0xdf, ext=0xff. Any ideas?

**Comment by kkrischker** [comment]
Just checked the fuses again: low fuse of 0x62 means that a clock divider by 8 is activated. The low fuse should be 0xe2, so that the device runs with 8 MHz.

**Comment by ivankravets** [comment]
Should be fixed in the latest release
