### ISSUE TITLE
Please wait while upgrading PlatformIO

### ISSUE THREAD

**Issue by Thijxx** [platformio/platform-atmelavr#59]
Checking for updates on all platforms for every upload after each code change is overkill. +90% of all my waiting is done at this screen.
I tried to turn is off, there is an option for "Automatically Update PlatformIO IDE" but that does something else.

![screenshot from 2017-07-24 20-43-18](https://user-images.githubusercontent.com/3355823/28539081-c8405fec-70b0-11e7-871b-51f4684d2dd5.png)

**Comment by ivankravets** [comment]
http://docs.platformio.org/en/latest/faq.html#multiple-pio-cores-in-a-system
