### ISSUE TITLE
Manchester lib fails on ATTiny

### ISSUE THREAD

**Issue by surdu** [platformio/platform-atmelavr#71]
I am using some RF modules like in [this tutorial](http://www.instructables.com/id/Attiny85-RF-Transmitter-to-Arduino-Uno-Receiver-Ma/) to transmit some data around, and some LED to indicate status. The TX/RX code is very similar to the one in the tutorial, except the RX is on the ATTiny so not using Serial.

When I compile & upload my RX code to the ATTiny using Arduino, all works well, but when I do it using Platform.io, the radio part stops working. LEDs continue to work fine.

My suspicion is that in Platform.io some definitions are wrong and the Manchester lib being very dependent of a lot of [compile](https://github.com/mchr3k/arduino-libs-manchester/blob/master/Manchester.cpp#L77) [time](https://github.com/mchr3k/arduino-libs-manchester/blob/master/Manchester.cpp#L289) [flags](https://github.com/mchr3k/arduino-libs-manchester/blob/master/Manchester.cpp#L364), does not configure itself properly. 

Unfortunately I don't have the skills to debug this issue further but I can help with any information one would need to fix this.

**Comment by ivankravets** [comment]
Could you provide source code with `platformio.ini` to reproduce this issue?

**Comment by surdu** [comment]
Unfortunately, platform IO went into an "installing/restarting" loop, so I had to uninstall it. 

The code in the linked tutorial should do the trick.

**Comment by ivankravets** [comment]
> Unfortunately, PlatformIO went into an "installing/restarting" loop, so I had to uninstall it.

This issue was fixed in related Python's Arrow library. Please try VSCode for PlatformIO and provide a project to reproduce the issue.
