### ISSUE TITLE
digispark-tiny platform: SPI.h not found 

### ISSUE THREAD

**Issue by dontsovcmc** [platformio/platform-atmelavr#74]
### Configuration

**Operating system**:
MacOS, Visual Studio Code (Windows 10x64 also)
**PlatformIO Version**:
PlatformIO, version 3.5.0b3

### Description of problem
I got error when build project that depends SPI.h
`src/main.cpp:2:17: fatal error: SPI.h: No such file or directory`

#### Steps to Reproduce
1. Project for Digistump Digispark 16Mhz
2. Add "SPI.h" header or add library that included "SPI.h"

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```
[env:digispark-tiny]
platform = atmelavr
board = digispark-tiny
framework = arduino
```

**Source file to reproduce issue:**
```
#include <Arduino.h>
#include "SPI.h"
void setup() {
    // put your setup code here, to run once:
}

void loop() {
    // put your main code here, to run repeatedly:
}
```

**Comment by ivankravets** [comment]
The same with Arduino IDE. It seems that need to use custom SPI library
![screen shot 2017-11-27 at 01 19 04](https://user-images.githubusercontent.com/1760209/33245469-fdc1dbe2-d310-11e7-98ad-ffef77a32808.png)
