### ISSUE TITLE
Toolchain does not recognize -std=gnu++14 build flag

### ISSUE THREAD

**Issue by leventesen** [platformio/platform-atmelavr#87]
Toolchain does not recognize -std=gnu++14 build flag.
It converts the flag to -std=gnu++1y

**Comment by ivankravets** [comment]
How did you pass it?

**Comment by leventesen** [comment]
That was long time ago, I forgot the details. After searching I had noticed that toolchain doesn't support C++14

**Comment by ivankravets** [comment]
Thanks! I close this issue, maybe, Microchip will update toolchain later
