### ISSUE TITLE
Build success when sketch is too big

### ISSUE THREAD

**Issue by vshymanskyy** [platformio/platform-atmelavr#93]
![image](https://user-images.githubusercontent.com/1506708/39866065-b20bcdf2-5457-11e8-8871-a9c4abc04a23.png)

**Comment by ivankravets** [comment]
Thanks! 😊 

Resolved in https://github.com/platformio/platformio-core/commit/bfc94d36e36bc9e2164734cf3894241db1a4831e (unified memory usage checker and reporter)

![screen shot 2018-06-04 at 14 26 36](https://user-images.githubusercontent.com/1760209/40915081-5ccc07ac-6803-11e8-8feb-67e5a195a6bb.png)
