### ISSUE TITLE
Adafruit ItsyBitsy 32u4 missing

### ISSUE THREAD

**Issue by avilleret** [platformio/platform-atmelavr#94]
as reported here : https://github.com/platformio/platformio-core/issues/1547 

the Adafruit's ItsyBitsy 32u4 board is missing

could you please add it ?

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platform-atmelavr/commit/84f485f6e51b0b8ab8b6c26052a5c2907d1df0e9
